### PR TITLE
Add more tests. Addressing #2

### PR DESCRIPTION
**Pull request by PabloReszczynski**
These are the tests I could came up, addressing both good and bad behavior of the macro usability.
Feel free to review and comment.

### CODE REVIEW

**Review by bradcypert — APPROVED** [review]

**Comment by bradcypert** [comment]
@PabloReszczynski this is great! Unrelated question: Do you find any value in this macro/writing tests this way?

**Comment by PabloReszczynski** [comment]
What do you mean by that?

**Comment by bradcypert** [comment]
Do you think the macro that you wrote tests for is valuable? I end up using it quite a bit, but I don't regularly associate with too many other Clojure developers. I was curious if you see value in it as well.

**Comment by PabloReszczynski** [comment]
I think tests written this way are more readable and easy to reason about. Having used cucumber/BDD in other projects I have become accustomed to use the way of testing of "Given-When".
The killer feature I think could bring a lot of attention to this project would be to wrap existing test frameworks like `clojure.test` or `midje` into this macro.

**Comment by bradcypert** [comment]
That's a very, very helpful response. Thank you :) Perhaps I'll investigate that going forward.

**Pull request merged**
